import React, { useState, useEffect } from 'react';
import Head from 'next/head';
import styles from "./styles.module.scss";

const Layout = () => {
  
  return (
    <>
      <Head>
        <title>Aqua City</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.layout}>

      </div>
    </>
  );
};

export default Layout;
