import React, { useState, useEffect } from 'react';
import Head from 'next/head';
import styles from './styles.module.scss';
import Header from '../Header';
import Controls from '../Controls';
import NavBars from '../NavBars';
import ContextProvider from '../../contants/Context';
import ViewControl from '../ViewControl';

const Layout = ({ children }) => {
  return (
    <>
      <ContextProvider>
        <Head>
          <title>Aqua City</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        <div className={styles.layout}>
          <Header />
          <Controls />
          <ViewControl />
          {children}
        </div>
      </ContextProvider>
    </>
  );
};

export default Layout;
