import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Containers from "./containers";
import Ground from "./mat-bang";
import Sliders from "./phan-khu/Slider";
import Ecological from "./sinh-thai";
import Utilities from "./tien-ich";
import HomePage from "./trang-chu";
import Position from "./vi-tri";

export default function Home() {
  return (
    <div
      style={{
        width: "100%",
        height: "100vh",
        overFlow: "hidden",
      }}
    >
      <Head>
        <title>Aqua City</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Containers/> */}
      {/* <HomePage /> */}
      {/* <Ground /> */}
      <Sliders />
      {/* <Position /> */}
      {/* <Ecological /> */}
      {/* <Utilities /> */}
    </div>
  );
}
